version: '3.8'

services:
  telegram-monitor:
    build: .
    container_name: telegram_monitor_control
    restart: unless-stopped

    # Змінні оточення
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Kiev
      - TELEGRAM_LOG_LEVEL=INFO

    # Монтування томів
    volumes:
      # Конфігурація (можна редагувати ззовні)
      - ./config:/app/config
      # Логи (зберігаються між перезапусками)
      - ./logs:/app/logs
      # Дані сесії Telegram
      - ./data:/app/data
      # Backup конфігурацій
      - ./backups:/app/backups
   #   - .:/app

    # Мапінг портів
    ports:
      - "8000:8000"

    # Обмеження ресурсів
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.2'

    # Перевірка здоров'я
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/monitor/status')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Логування
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    # Мережі
    networks:
      - telegram_network

  # Додатковий сервіс для генерації сесії (запускається окремо)
  session-generator:
    build: .
    container_name: telegram_session_generator
    profiles: ["tools"]  # Не запускається з основним compose

    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Kiev

    volumes:
      - ./config:/app/config
      - ./data:/app/data

    # Інтерактивний режим для введення коду
    stdin_open: true
    tty: true

    command: ["python", "generate_session.py"]

    networks:
      - telegram_network

networks:
  telegram_network:
    driver: bridge
    name: telegram_monitor_net